name: Macos-GUI
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Ekran Paylaşımını ve VNC'yi Hazırla
        run: |
          # 1. Ekran paylaşımını aktif et ve şifreyi 123456 yap
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw 123456 -restart -agent -privs -all
          
          # 2. Ekranın uyumasını engelle (Bağlanıyor'da kalmaması için kritik)
          sudo caffeinate -u -t 3600 &
          
          # 3. Ekran çözünürlüğünü standart hale getir
          sudo /usr/bin/defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool NO
          
      - name: Cloudflared Kur ve Tüneli Başlat
        run: |
          brew install cloudflared
          # Tüneli arka planda başlat ve logları ekrana bas
          cloudflared tunnel --url tcp://localhost:5900
